Kowhiri.Web/Models/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Kowhiri.Web.Models
{
    public class ContactViewModel
    {
        [Display(Name = "Name")]
        [Required]
        public string FirstName { get; set; }


        [Display(Name = "Phone")]
        public string PhoneNumber { get; set; }

        [EmailAddress]
        [Required]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Message")]
        public string Enquiry { get; set; }

        [Required(ErrorMessage = "You must confirm you are not a robot")]
        public string RecaptchaResponse { get; set; }
    }
}

Kowhiri.Web/Controllers/ContactController.cs
using System;
using System.Configuration;
using System.Net.Mail;
using System.Web.Mvc;
using Kowhiri.Web.Extensions;
using Kowhiri.Web.Helpers;
using Kowhiri.Web.Models;
using Umbraco.Web.Mvc;

namespace Kowhiri.Web.Controllers
{
    public class ContactController : SurfaceController
    {
        // GET: Contact
        public ActionResult GetForm()
        {
            return PartialView("Index", new ContactViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostForm(ContactViewModel model)
        {
            var reCapture = ReCaptcha.Validate(model.RecaptchaResponse);

            if (!reCapture.Success)
            {
                TempData["validationMessage"] = "Recapture validation failed";
                return Json(new
                {
                    success = false,
                    html = this.RenderPartialViewToString("Index", model)
                });
            }

            //Check if the dat posted is valid (All required's & email set in email field)
            if (!ModelState.IsValid)
            {
                //Not valid - so lets return the user back to the view with the data they entered still prepopulated
                return Json(new
                {
                    success = false,
                    html = this.RenderPartialViewToString("Index", model)
                });
            }

            //Generate an email message object to send
            MailMessage email = new MailMessage(ConfigurationManager.AppSettings["Kowhiri.ContactFromEmail"], ConfigurationManager.AppSettings["Kowhiri.ContactToEmail"])
            {
                Subject = ConfigurationManager.AppSettings["Kowhiri.ContactSubject"],
                Body = $"Name : {model.FirstName} <br/> Phone : {model.PhoneNumber} <br/> Email : {model.Email} <br/> Message : {model.Enquiry}"
            };

            try
            {
                //Connect to SMTP credentials set in web.config
                SmtpClient smtp = new SmtpClient();
                //Try & send the email with the SMTP settings
                smtp.Send(email);
            }
            catch (Exception ex)
            {
                TempData["validationMessage"] = "Failed to send email";
                return Json(new
                {
                    success = false,
                    html = this.RenderPartialViewToString("Index", model),
                    message = ex.Message
                });

            }

            //Update success flag (in a TempData key)
            TempData["IsSuccessful"] = true;

            //All done - lets redirect to the current page & show our thanks/success message
            return Json(new
            {
                success = true,
                html = this.RenderPartialViewToString("Index", model)
            });
        }

    }
}

Kowhiri.Web/Controllers/ContentController.cs
using System.Web.Mvc;
using DevTrends.MvcDonutCaching;
using Umbraco.Web;
using Umbraco.Web.Mvc;

namespace Kowhiri.Web.Controllers
{
    public class ContentController : SurfaceController
    {
        // the cache is cleared upon change in the CMS
        [DonutOutputCache(CacheProfile = "OneHour")]
        public ActionResult Index(int id, object model = null, string viewName = "Index")
        {
            ViewBag.Content = Umbraco.TypedContent(id);

            if (ViewBag.Content == null)
            {
                Response.StatusCode = 404;
                return new HttpNotFoundResult();
            }

            if (viewName == null)
            {
                viewName = ViewBag.Content.ContentType.Alias;
            }

            return PartialView(viewName, model);
        }

      
    }
}

Kowhiri.Web/Views/BlogArticle.cshtml
@using Kowhiri.Web.Constants
@using Kowhiri.Web.Extensions
@inherits UmbracoTemplatePage
@{
    Layout = "Partials/_Layout.cshtml";
    ViewBag.ClassName = "blog-single-page";
}

<div class="page-content blog-single">
    <div class="banner std">
        <div class="banner-img">
            @Model.Content.GetImage("mainImage")
        </div>
    </div>
    <div class="column-wrapper">
        <div class="column-3of4">
            <div class="article-container">
                <span class="article-date">@Model.Content.CreateDate.ToString(DateFormats.ShortDate)</span>
                <h2 class="article-title">@Model.Content.Name</h2>
                <div class="article-content">
                    @Model.Content.GetPropertyValue("content")
                </div>
                <a class="btn-back" href="@Umbraco.NiceUrl(1110)">&lsaquo; Back to Articles</a>
            </div>
        </div>
 

            @{

            var featuredArticles = Umbraco.GetContentFromIds(Umbraco.TypedContent(1110).GetPropertyValue("featuredArticles")).Where(x => x.Id != Model.Content.Id);

            Html.RenderPartial("/Views/Partials/MoreArticles.cshtml", featuredArticles);
            }

    </div>
</div>

Kowhiri.Web/Views/BlogContainer.cshtml
@using Kowhiri.Web.Constants
@using Kowhiri.Web.Extensions
@inherits UmbracoTemplatePage
@{
    Layout = "Partials/_Layout.cshtml";
    ViewBag.ClassName = "blog-landing-page";
}

<!-- banner.std -->
<div class="banner std">
    <div class="banner-content">
        <div class="caption">
            <h1>@Model.Content.Name</h1>
        </div>
    </div>
    <div class="banner-img">
        @Model.Content.GetImage("bannerImage")
    </div>
</div>

@{
    var blogUrl = Umbraco.NiceUrl(1110);
    blogUrl = blogUrl.Substring(0, blogUrl.Length - 1);

    var featuredArticles = Umbraco.GetContentFromIds(Model.Content.GetPropertyValue("featuredArticles"));

    var selectedPage = 1;
    Int32.TryParse(Request["page"] ?? "1", out selectedPage);

    var blogPageSize = Model.Content.GetPropertyValue<int>("pageSize");
    var blogArticles = Umbraco.TypedContentAtXPath("//blogArticle").OrderByDescending(x => x.CreateDate);

    var totalPages = (blogArticles.Count() + blogPageSize - 1) / blogPageSize;

    if (selectedPage > totalPages || selectedPage < 1)
    {
        selectedPage = 1;
    }

    var blogArticlesToShow = blogArticles
        .Skip(blogPageSize * (selectedPage - 1))
        .Take(blogPageSize);
}

<div class="page-content blog-landing">
    <div class="column-wrapper">
        <div class="column-3of4 blog-articles">
            <h3>Recent articles</h3>
            @foreach (var article in blogArticlesToShow)
            {
                var image = article.GetImage("mainImage");
                    <div class="article-single">
                        
                            <a class="hover" href="@article.Url"></a>
                            <div class="article-header">
                                @if (image != MvcHtmlString.Empty)
                                {
                                @image
                                }
                                else
                                {
                                    <img src="~/images/blog-placeholder-generic.jpg" alt="Kinly blog - image coming soon" />
                                }
                            </div>
                       
                        <div class="article-content">
                            <h3>@article.Name</h3>
                            @Umbraco.Truncate(article.GetPropertyValue<string>("content"), 500, true)
                        </div>
                    </div>
            }

            <!-- Pager -->
            <div class="pager-container">
                @if (totalPages > 1)
                {
                    <ul class="pager">
                        @for (var i = 1; i <= totalPages; i++)
                        {
                            <li class="@(selectedPage == i ? "active" : string.Empty)">
                                <a class="" href="@(i > 1 ? blogUrl + "?page=" + i : blogUrl + "/")">@i</a>
                            </li>
                        }
                    </ul>
                }
            </div>
        </div>

        

        <!-- More articles -->
        @{
            Html.RenderPartial("/Views/Partials/MoreArticles.cshtml", featuredArticles);
        }
    </div>
</div>

Kowhiri.Web/Views/BlogYear.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.BlogYear>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

Kowhiri.Web/Views/Contact.cshtml
@using Kowhiri.Web.Extensions
@using Kowhiri.Web.Utilities
@inherits UmbracoTemplatePage
@{
    Layout = "Partials/_Layout.cshtml";
    ViewBag.ClassName = "contact-page";
}

<!-- banner.std -->
<div class="banner std">
    <div class="banner-content">
        <div class="caption">
            <h1>@CurrentPage.Name</h1>
        </div>
    </div>
    <div class="banner-img">
        @Model.Content.GetImage("bannerImage")
    </div>
</div>

<div class="page-content contact">
    <div class="column-wrapper">
        <div class="column-2of3">
            <h3><span class="circle badge icon icon-airplane"></span>Send us a message</h3>
            @Model.Content.GetPropertyValue("mainContent")
            <div class="ajax-replace">
                @*
                    don't put content in the here (the ajax-replace div), it will be removed after form submission
                *@

                @{
                    Html.RenderAction("GetForm", "Contact");
                }
            </div>
        </div>
        <div class="column-1of3 contact-details">
            <!-- Address -->
            <div class="contact-single">
                <div class="contact-label">
                    <h3><span class="circle badge icon icon-map"></span>Address</h3>
                </div>
                <div class="contact-detail">
                    <p>@Model.Content.GetPropertyValue("address")</p>
                </div>
            </div>
            <!-- Phone -->
            <div class="contact-single">
                <div class="contact-label">
                    <h3><span class="circle badge icon icon-phone"></span>Phone</h3>
                </div>
                <div class="contact-detail">
                    <p>@Model.Content.GetPropertyValue("phone")</p>
                </div>
            </div>
            <!-- Email -->
            <div class="contact-single">
                <div class="contact-label">
                    <h3><span class="circle badge icon icon-envelope"></span>Email</h3>
                </div>
                <div class="contact-detail">
                    <p><a href="mailto:@Model.Content.GetPropertyValue("email")">@Model.Content.GetPropertyValue("email")</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{

    @{
        Bundles.Reference("validation");
    }
    <script>

        var widget;

        var verifyCallback = function () {
            $('#RecaptchaResponse').val(grecaptcha.getResponse(widget));
        }

        var onloadCallback = function() {

            widget = grecaptcha.render('Recaptcha',
            {
                'sitekey': '@(AppSettings.Get<string>("reCAPTCHA_SiteKey"))',
                'callback': verifyCallback
            });
        }

    </script>
    <script src='https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit'></script>
}

Kowhiri.Web/Views/Contact/Index.cshtml
@using System.Drawing
@using Kowhiri.Web.Controllers
@using Kowhiri.Web.Helpers
@using Kowhiri.Web.Utilities
@model Kowhiri.Web.Models.ContactViewModel


@if (Convert.ToBoolean(TempData["IsSuccessful"]))
{
    <h2 class="message-sent-title">Message sent!</h2>
    <p>Thanks for sending your message, we will get back to you shortly.</p>
}
else
{
    if (TempData["validationMessage"] != null)
    {
        <p class="error" style="color:red">@TempData["validationMessage"]</p>
    }

    using (Html.BeginUmbracoForm<ContactController>("Index"))
    {
        @Html.ValidationSummary(true)
        @Html.AntiForgeryToken()

        <p>
            @Html.TextBoxFor(x => x.FirstName, new { @placeholder = "Name" })
            @Html.ValidationMessageFor(x => x.FirstName)
        </p>
        <p>
            @Html.TextBoxFor(x => x.Email, new { @placeholder = "Email" })
            @Html.ValidationMessageFor(x => x.Email)
        </p>
        <p>
            @Html.TextBoxFor(x => x.PhoneNumber, new { @placeholder = "Phone" })
            @Html.ValidationMessageFor(x => x.PhoneNumber)
        </p>
        <p>
            @Html.TextAreaFor(x => x.Enquiry, new { @placeholder = "Message" })
            @Html.ValidationMessageFor(x => x.Enquiry)
        </p>

        <div class="recaptcha-wrapper">
            <div id="Recaptcha" class="g-recaptcha" data-sitekey="@(AppSettings.Get<string>("reCAPTCHA_SiteKey"))"></div>
            @Html.HiddenFor(x => x.RecaptchaResponse)
            @Html.ValidationMessageFor(x => x.RecaptchaResponse)
        </div>

        <p>
            <input value="Submit" type="submit">
        </p>
    }
}

Kowhiri.Web/Views/Content.cshtml
@using Kowhiri.Web.Extensions
@inherits UmbracoTemplatePage
@{
    Layout = "Partials/_Layout.cshtml";
    ViewBag.ClassName = "content-page";

    if (Model.Content.HasValue("cSSClassName"))
    {
        ViewBag.ClassName = Model.Content.GetPropertyValue("cSSClassName");
    }

}

<!-- banner.std -->
<div class="banner std">
    <div class="banner-content column-wrapper">
        <div class="caption">
            <h1>@CurrentPage.Name</h1>
        </div>
    </div>
    <div class="banner-img">
        @Model.Content.GetImage("bannerImage")
    </div>
</div>
<!-- page-content -->
<div class="page-content generic">
    <div class="column-wrapper">
        @Model.Content.GetPropertyValue("mainContent")
    </div>
</div>

Kowhiri.Web/Views/Content/FooterLinks.cshtml
@using Kowhiri.Web.Extensions
@model object

@{
    var umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
    var content = (ViewBag.Content as IPublishedContent);
}

<ul>
    <li class="btn-pricing">
        <a href="/#pricing">Pricing</a>
    </li>
    @foreach (var page in umbracoHelper.GetContentFromIds(content.GetPropertyValue("links")))
    {
        <li>
            <a href="@page.Url">@page.Name</a>
        </li>
    }
</ul>

Kowhiri.Web/Views/Content/Index.cshtml
@model object

@{
    //var umbracoHelper = new UmbracoHelper(UmbracoContext.Current);

    var content = (ViewBag.Content as IPublishedContent);

}

@content.GetPropertyValue("content")

Kowhiri.Web/Views/Error404.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = "Partials/_Layout.cshtml";
    ViewBag.ClassName = "error-page";
}

<!-- banner.std -->
<div class="banner std">
    <div class="banner-content column-wrapper">
        <div class="caption">
            <h1>@CurrentPage.Name</h1>
        </div>
    </div>
    <div class="banner-img">
        <img src="/images/banner-generic.jpg" alt="Kinly makes creating a Will simple, without the need for a lawyer" />
    </div>
</div>
<!-- page-content -->
<div class="page-content error-404">
    <div class="column-wrapper">
        @*@Model.Content.GetPropertyValue("mainContent")*@
        <p>There was an error while processing your request.</p>
        <a class="btn-back" href="/" title="Back to homepage">&lsaquo; Back to Home</a>
    </div>
</div>

Kowhiri.Web/Views/FAQ.cshtml
@using Kowhiri.Web.Extensions
@inherits UmbracoTemplatePage
@{
    Layout = "Partials/_Layout.cshtml";
    ViewBag.ClassName = "faq-page";
}

<!-- banner.std -->
<div class="banner std">
    <div class="banner-content">
        <div class="caption">
            <h1>@Model.Content.Name</h1>
        </div>
    </div>
    <div class="banner-img">
        @Model.Content.GetImage("bannerImage")
    </div>
</div>

<div class="page-content faq">
    <div class="column-wrapper">
        <div role="tablist" class="accordion faq-list">
            @foreach (var faq in Model.Content.Children())
            {
                <div class="faq-header">
                    <h3>@faq.Name</h3><span class="badge circle icon icon-chevron-down"></span>
                </div>
                <div class="faq-content">
                    @faq.GetPropertyValue("answer")
                </div>
            }
        </div>
    </div>
</div>

Kowhiri.Web/Views/Home.cshtml
@using Kowhiri.Web.Extensions
@inherits UmbracoTemplatePage
@{
    Layout = "Partials/_Layout.cshtml";
    ViewBag.ClassName = "home-page";
}

    <!-- HERO BANNER -->
    <div class="banner hero">
        <div class="banner-content column-wrapper">
            <div class="caption">
                <h1>@Html.Raw(Model.Content.GetPropertyValue("title"))</h1>
            </div>
            <img class="accessory" src="/images/phone.png" alt="Kinly app on an iPhone" />
        </div>
        <div class="banner-img">
            @Model.Content.GetImage("bannerImage")
        </div>
    </div>

    <!-- app download buttons -->
    <div class="section-container hero-app-download">
        <div class="column-wrapper">
            @{
                Html.RenderPartial("/views/partials/downloadlinks.cshtml");
            }
        </div>
    </div>

    <!-- INTRO PARAGRAPH -->
    <div class="section-container intro">
        <div class="column-wrapper">
            <div class="column-4of4">
                @Model.Content.GetPropertyValue("mainContent")
            </div>
        </div>
    </div>

    <!-- TAKE CARE OF YOUR WILL NOW -->
    @{
        var reasons = Umbraco.TypedContent(1095);

        if (reasons != null)
        {
            <div class="section-container product-outlines">
                <div class="column-wrapper">
                    <h2>@reasons.Name</h2>

                    @foreach (var reason in reasons.Children())
                    {
                        <div class="outline-single reason">
                            <div class="column-3of4 text">
                                <h3>@reason.Name</h3>
                                @reason.GetPropertyValue("content")
                            </div>
                            <div class="column-1of4 imagery">
                                <div class="badge circle">
                                    <span class="icon @reason.GetPropertyValue("cSSClassName")"></span>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        }

        <div class="section-container supporting-imagery">
            @Model.Content.GetImage("secondaryBanner")
        </div>
            <!-- OTHER FEATURES -->
            var features = Umbraco.TypedContent(1094);

            if (features != null)
            {
            <div class="section-container other-features">
                <div class="column-wrapper">
                    <h2>@features.Name</h2>

                    @foreach (var feature in features.Children())
                    {
                        <div class="column-1of3 feature-single">
                            <div class="imagery">
                                <div class="badge circle">
                                    <span class="icon @feature.GetPropertyValue("cSSClassName")"></span>
                                </div>
                            </div>
                            <div class="text">
                                <h3>@feature.Name</h3>
                                @feature.GetPropertyValue("content")
                            </div>
                        </div>
                    }
                </div>
            </div>
            }

            <!-- PRICING -->
            <div id="pricing" class="section-container pricing-outlines">
                <div class="column-wrapper">
                    <h2>Pricing</h2>
                    @Model.Content.GetPropertyValue("pricingIntro")
                    @Model.Content.GetPropertyValue("pricing")
                </div>
            </div>
            }

Kowhiri.Web/Views/Partials/DownloadLinks.cshtml
@{
    Html.RenderAction("Index", "Content", new { id = 1129, viewName = "Index", model = new object() });
}

Kowhiri.Web/Views/Partials/Footer.cshtml
<!-- FOOTER -->
<footer>
    <div class="footer-container section-download">
        <div class="footer-content column-wrapper">
            <h2>Get life sorted</h2>
            @{
                Html.RenderPartial("/views/partials/downloadlinks.cshtml");
            }
            <p class="legal-credit">Powered by Greatwill</p>
        </div>
    </div>
    <div class="footer-container section-links">
        <div class="footer-content column-wrapper">
            @{
                Html.RenderAction("Index", "Content", new { id = 1089, viewName = "FooterLinks", model = new object() });
            }
            @{
                // Edit in CMS > Managed Content > Shared Content > Footer
                // view name and model are option params
                var copyright = Html.Action("Index", "Content", new { id = 1080, viewName = "Index", model = new object() });
            }
        </div>
    </div>
    <div class="footer-container section-legal">
        <div class="footer-content column-wrapper">
            <div class="column-1of2 legal-copyright">
                @Html.Raw(copyright.ToString().Replace("##YEAR##", DateTime.UtcNow.Year.ToString()))
                <!-- Managed Content > Shared Content > Footer -->
            </div>
            <ul class="column-1of2 legal-terms">
                <li><a href="/privacy-policy" title="Privacy Policy">Privacy Policy</a></li>
                <li><a href="/terms-of-use" title="Terms of Use">Terms of Use</a></li>
            </ul>
        </div>
    </div>
</footer>

Kowhiri.Web/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Kowhiri.Web/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Kowhiri.Web/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

Kowhiri.Web/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@Html.Raw(Model.value)

Kowhiri.Web/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

Kowhiri.Web/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }
    
    <img src="@url" alt="@Model.value.altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

Kowhiri.Web/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

Kowhiri.Web/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();

    markup = markup.Replace("#value#", Model.value.ToString());
    markup = markup.Replace("#style#", Model.editor.config.style.ToString());

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}